name: PR preview

on:
  pull_request:
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - '.env'
      - 'jsconfig.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' && github.event.action != 'merged' }}
    steps:
      - uses: actions/checkout@v2
      - name: Replace homepage URL
        run: sed -i "s/https:\/\/valhalla.openstreetmap.de/https:\/\/valhalla-app-tests.gis-ops.com\/${PULL_REQUEST_NUMBER}/g" package.json
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: 🔧 Create build
        run: |
          npm install
          npm run build
      - name: 🚀 Deploy
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          rsync -r --delete --rsync-path="mkdir -p ${{ vars.HOST_TARGET_DIR }}/$PULL_REQUEST_NUMBER && rsync" -e "ssh -o StrictHostKeyChecking=no" ./build/ ${{ vars.HOST_USERNAME }}@${{ vars.HOST_IP }}:${{ vars.HOST_TARGET_DIR }}/$PULL_REQUEST_NUMBER
      - name: Preview URL
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: "https://valhalla-app-tests.gis-ops.com/$PULL_REQUEST_NUMBER"
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"The preview is ready! 🚀 You can view it here: $URL \"}" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PULL_REQUEST_NUMBER}/comments
      - name: Clean up
        if: ${{ github.event.action == 'closed' || github.event.action == 'merged' }}
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh ${{ vars.HOST_USERNAME }}@${{ vars.HOST_IP }} 'rm -rf ${{ vars.HOST_TARGET_DIR }}/$PULL_REQUEST_NUMBER'
