name: PR preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - '.env'
      - 'jsconfig.json'

env:
  PULL_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  clean-up:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: remove preview
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh -o StrictHostKeyChecking=no ${{ vars.HOST_USERNAME }}@${{ vars.HOST_IP }} 'rm -rf ${{ vars.HOST_TARGET_DIR }}/$PULL_NUMBER'
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}
    steps:
      - uses: actions/checkout@v2
      - name: Replace homepage URL
        run: sed -i "s/https:\/\/valhalla.openstreetmap.de/https:\/\/valhalla-app-tests.gis-ops.com\/${PULL_NUMBER}/g" package.json
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: 🔧 Create build
        run: |
       #   npm install
        #  npm run build
      - name: 🚀 Deploy
        run: |
   #       eval $(ssh-agent -s)
  #         ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
 #          rsync -r --delete --rsync-path="mkdir -p ${{ vars.HOST_TARGET_DIR }}/$PULL_NUMBER && rsync" -e "ssh -o StrictHostKeyChecking=no" ./build/ ${{ vars.HOST_USERNAME }}@${{ vars.HOST_IP }}:${{ vars.HOST_TARGET_DIR }}/$PULL_NUMBER
      - name: Preview URL
 #       if: success()
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const body = `Preview is ready! 🚀 You can view it here: https://valhalla-app-tests.gis-ops.com/${{ github.event.pull_request.number }}`;
            const { data } = await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
      
